<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIB-DES-00567" ignored="0" name="Regression Test" tests="4" failures="1" timestamp="29 Aug 2018 06:51:19 GMT" time="12.866" errors="0">
  <testcase name="TC_002" time="2.108" classname="com.wibmo.LoginAPI.tests.TC_002">
    <failure type="java.lang.AssertionError" message="expected [BAD_PWD] but found [BLOCKED]">
      <![CDATA[java.lang.AssertionError: expected [BAD_PWD] but found [BLOCKED]
at com.wibmo.LoginAPI.tests.TC_002.TC_002(TC_002.java:34)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TC_002 -->
  <testcase name="IAP_001" time="2.465" classname="com.wibmo.IAP.tests.IAP_001"/>
  <testcase name="IAP_002" time="1.692" classname="com.wibmo.IAP.tests.IAP_002"/>
  <testcase name="TC_001" time="12.836" classname="com.wibmo.LoginAPI.tests.TC_001"/>
</testsuite> <!-- Regression Test -->
