<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIB-DES-00567" ignored="0" name="test 2" tests="1" failures="1" timestamp="29 Aug 2018 06:54:21 GMT" time="2.204" errors="0">
  <testcase name="TC_002" time="2.194" classname="com.wibmo.LoginAPI.tests.TC_002">
    <failure type="java.lang.AssertionError" message="expected [BAD_PWD] but found [BLOCKED]">
      <![CDATA[java.lang.AssertionError: expected [BAD_PWD] but found [BLOCKED]
at com.wibmo.LoginAPI.tests.TC_002.TC_002(TC_002.java:34)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- TC_002 -->
</testsuite> <!-- test 2 -->
